In [52]:
# Define the documents as a dictionary where keys are document titles and values are document content
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}

In [53]:
# get the keys of the documents and store it in the list
key_documents = list(documents.keys())

# display the list of the key documents
print(key_documents)

['Article: Pandas Basics', 'Tutorial: Data Visualization', 'Case Study: Sales Analysis']


In [54]:
# Extract the category from the key documents and store it in a list
categories = [title.split(':')[0] for title in documents.keys()]

# Display the list of categories
print(categories)

['Article', 'Tutorial', 'Case Study']


In [55]:
# Extract the content values and put them in a list
document_content_list = list(documents.values())

# Display the list of document content
print(document_content_list)

['This article covers the basics of using Pandas in Python.', 'Learn about data visualization techniques with Python libraries.', 'Analyze sales data using Python for a real-world case study.']


In [56]:
# Gather the set of all unique terms from the list content of document and diplay the result
unique_terms = set()

# Iterate through each document content to extract unique terms
for content in document_content_list:
    terms = content.split()
    unique_terms.update(terms)

#Display the result
unique_terms = list(unique_terms)
print(unique_terms)

['using', 'Python', 'basics', 'visualization', 'Pandas', 'for', 'case', 'This', 'covers', 'sales', 'with', 'in', 'Python.', 'about', 'the', 'article', 'real-world', 'techniques', 'Analyze', 'Learn', 'a', 'of', 'data', 'libraries.', 'study.']


In [57]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

# your code here
for key in unique_terms: 
    doc_term_matrix[key] = []
    for doc in key_documents:
        if key in documents[doc]:
            doc_term_matrix[key].append(1)
        else: 
            doc_term_matrix[key].append(0)


# display the result of the matrix
doc_term_matrix



{'using': [1, 0, 1],
 'Python': [1, 1, 1],
 'basics': [1, 0, 0],
 'visualization': [0, 1, 0],
 'Pandas': [1, 0, 0],
 'for': [0, 0, 1],
 'case': [0, 0, 1],
 'This': [1, 0, 0],
 'covers': [1, 0, 0],
 'sales': [0, 0, 1],
 'with': [0, 1, 0],
 'in': [1, 0, 1],
 'Python.': [1, 0, 0],
 'about': [0, 1, 0],
 'the': [1, 0, 0],
 'article': [1, 0, 0],
 'real-world': [0, 0, 1],
 'techniques': [0, 1, 0],
 'Analyze': [0, 0, 1],
 'Learn': [0, 1, 0],
 'a': [1, 1, 1],
 'of': [1, 0, 0],
 'data': [0, 1, 1],
 'libraries.': [0, 1, 0],
 'study.': [0, 0, 1]}

In [68]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print('==== Matrices Checking by each contents ====')
print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2
print('This the result after multiplication of matrices' , v3)

# display the content document from the result

[result for result in v3*docs_array if result]

==== Matrices Checking by each contents ====
[1 0 0]
[1 1 1]
-------
This the result after multiplication of matrices [1 0 0]


['This article covers the basics of using Pandas in Python.']

In [69]:
# find the document for those have at least one word
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['data'])    
v2 = np.array(doc_term_matrix['Python'])

print('==== Matrices Checking by each contents ====')
print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 | v2
print('This the result after multiplication of matrices' , v3)

# display the content document from the result
#docs_array[v3]
[result for result in v3*docs_array if result]

==== Matrices Checking by each contents ====
[0 1 1]
[1 1 1]
-------
This the result after multiplication of matrices [1 1 1]


['This article covers the basics of using Pandas in Python.',
 'Learn about data visualization techniques with Python libraries.',
 'Analyze sales data using Python for a real-world case study.']